"""empty message

Revision ID: 2bc31ea34c8f
Revises: 016b9025f91a
Create Date: 2021-02-05 09:34:20.910591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc31ea34c8f'
down_revision = '016b9025f91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('c_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'c_time')
    # ### end Alembic commands ###
