"""empty message

Revision ID: 319f912c087d
Revises: 2bc31ea34c8f
Create Date: 2021-02-07 17:50:03.372603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319f912c087d'
down_revision = '2bc31ea34c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msg_name', sa.String(length=32), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('c_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hello_message_c_time'), 'hello_message', ['c_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hello_message_c_time'), table_name='hello_message')
    op.drop_table('hello_message')
    # ### end Alembic commands ###
